---
title: "Project1.Rmd"
author: "Dizhou Wu"
date: '2023-09-29'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project 1

```{r}
# Load library
#library(MASS)
library(ROCR)
library(ggplot2)
#suppressMessages(library(tidyverse))
library(foreign)
library(statmod)
library(dplyr)
library(caret)
suppressMessages(library(car))
```

```{r}
# Load data
source("http://www.openintro.org/stat/data/cdc.R")
```

```{r}
# Save as .txt file
write.table(cdc, file = "cdc.txt", sep = "\t", row.names = FALSE)
```


```{r}
#cdc
```

```{r}
cdc$wl <- cdc$weight - cdc$wtdesire
#cdc$wl <- sign(cdc$wl)*sqrt(abs(cdc$wl))
```

```{r}
# Fit a logistic regression model
m1 <- glm(exerany ~ wl + age + genhlth + hlthplan, data = cdc, family = binomial)
summary(m1)
```

```{r}
# 95% Confidence Interval
conf_int <- confint(m1, level = 0.95)
print(conf_int)
```



```{r}
# Quantile residual plot
qresiduals <- qresid(m1)
plot(m1$fitted.values, qresiduals, xlab="Fitted values", ylab="Quantile Residuals")
abline(h = 0, col = "red")
```




```{r}
# Assuming 'explanatory_var' is your explanatory variable of interest
plot(cdc$hlthplan, qresiduals, xlab="Explanatory Variable", ylab="Quantile Residuals")
abline(h = 0, col = "red")
```


```{r}
# Assuming 'explanatory_var' is your explanatory variable of interest
plot(cdc$genhlth, qresiduals, xlab="Explanatory Variable", ylab="Quantile Residuals")
abline(h = 0, col = "red")
```


```{r}
# Assuming 'explanatory_var' is your explanatory variable of interest
plot(cdc$age, qresiduals, xlab="Explanatory Variable", ylab="Quantile Residuals")
abline(h = 0, col = "red")
```


```{r}
# Assuming 'explanatory_var' is your explanatory variable of interest
plot(cdc$wl, qresiduals, xlab="Explanatory Variable", ylab="Quantile Residuals")
abline(h = 0, col = "red")
```

```{r}
# Cook's distance
cooks_d <- cooks.distance(m1)
plot(cooks_d, ylab="Cook's distance", xlab="Index")
#abline(h=c(0.5, 1), col="red")
```

```{r}
# Variance inflation factor
vif(m1)
```

```{r}
# Load library
library(MASS)

# Specify the starting model
m2 <- glm(exerany ~ wl + age + genhlth + hlthplan + smoke100 + gender + height, data = cdc, family = binomial)
summary(m2)
```


```{r}
# 95% Confidence Interval
conf_int <- confint(m2, level = 0.95)
print(conf_int)
```


```{r}
# Backward selection using BIC
backward_bic <- stepAIC(m2, scope = ~ .,
                      direction = "backward",
                      trace = 0, k = log(nrow(cdc)))

summary(backward_bic)
```

```{r}
# 95% Confidence Interval
conf_int <- confint(backward_bic, level = 0.95)
print(conf_int)
```


```{r}
# ROC curve for backward_bic
pred <- prediction(backward_bic$fitted.values, cdc$exerany)
perf <- performance(pred,"tpr","fpr")
performance(pred, "auc")@y.values
data.frame(fpr = perf@x.values[[1]],
tpr = perf@y.values[[1]]) |>
ggplot(aes(x = fpr, y = tpr)) +
geom_line(lwd=1.5) +
geom_abline(slope = 1, intercept = 0, lty = 2,
lwd = 1.5) +
labs(x = "False positive rate (1 - Specificity)",
y = "True positive rate (Sensitivity)") +
theme_classic()
```

```{r}
# Create prediction and performance objects using your actual data
pred <- prediction(backward_bic$fitted.values, cdc$exerany)
perf <- performance(pred, "tpr", "fpr")

# Calculate distances to (0, 1)
distances <- sqrt((1 - perf@y.values[[1]])^2 + perf@x.values[[1]]^2)

# Identify the index of the closest point
min_index <- which.min(distances)

# Extract the best threshold
best_threshold <- perf@alpha.values[[1]][min_index]

# Display the best threshold
if (!is.na(best_threshold)) {
  print(paste("Best threshold is:", best_threshold))
} else {
  print("Could not find the best threshold.")
}
```





```{r}
# Get the predicted probabilities
predicted_probs <- predict(backward_bic, type = "response")

# Create a new column with predicted classes based on the 0.76 threshold
cdc$predicted_exerany <- ifelse(predicted_probs > best_threshold, 1, 0)

# Convert the actual and predicted values to factors
cdc$predicted_exerany <- factor(cdc$predicted_exerany)
cdc$exerany <- factor(cdc$exerany)

# Create the confusion matrix
confusionMatrix(cdc$predicted_exerany, cdc$exerany)
```


















